const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');
const {
  buildEngineFailureReview,
  buildReviewDocument,
  extractDecisionFromModelText,
  normalizeDecision
} = require('./review-format');

function truncate(text, max = 120000) {
  if (!text) return '';
  if (text.length <= max) return text;
  return `${text.slice(0, max)}\n\n...[truncated]`;
}

function buildReviewPrompt(payload) {
  const contract = payload.decisionContract || {};
  const allowed = (contract.allowedDecisions || ['APPROVE', 'REQUEST_CHANGES', 'REJECT']).join(', ');

  return [
    'You are the configured Layer 2 code reviewer for the agent-cowork (pixel-agent-desk) governance workflow.',
    'Evaluate the task specification, review request, and code diff.',
    'Return ONLY valid Markdown for REVIEWS/review_NNN.md using this exact header:',
    '',
    `# Reviewer Review: ${payload.taskId}`,
    '',
    `- **Reviewer**: ${payload.reviewer?.name || 'Grok Build'}`,
    `- **Decision**: <one of ${allowed}>`,
    '',
    'Then include sections:',
    '## 1. Review Summary',
    '## 2. Detailed Findings',
    '### Blocking Issues',
    '### Non-Blocking Notes',
    '### Optional Follow-ups',
    '## 3. Tradeoffs & Architectural Analysis',
    '',
    'The decision line must be exact, e.g. `- **Decision**: APPROVE`.',
    '',
    '--- TASK FILE ---',
    truncate(payload.task),
    '',
    '--- REVIEW REQUEST ---',
    truncate(payload.reviewRequest),
    '',
    '--- DIFF ---',
    truncate(payload.diff) || '(no diff patch provided)',
    ''
  ].join('\n');
}

async function callXaiReview({ payload, env = process.env }) {
  const apiKey = env.XAI_API_KEY || env.GROK_API_KEY;
  if (!apiKey) {
    throw new Error('XAI_API_KEY (or GROK_API_KEY) is required for REVIEWER_ENGINE=xai');
  }

  const model = env.REVIEWER_MODEL || 'grok-3-mini-beta';
  const baseUrl = (env.XAI_API_BASE_URL || 'https://api.x.ai/v1').replace(/\/$/, '');
  const prompt = buildReviewPrompt(payload);

  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      temperature: 0.2,
      messages: [
        {
          role: 'system',
          content: 'You are a strict software governance reviewer. Output Markdown only.'
        },
        { role: 'user', content: prompt }
      ]
    })
  });

  const responseText = await response.text();
  if (!response.ok) {
    throw new Error(`xAI API failed with ${response.status}: ${responseText}`);
  }

  const data = JSON.parse(responseText);
  const content = data?.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error('xAI API returned no message content');
  }

  const decision = extractDecisionFromModelText(content);
  if (!decision) {
    throw new Error('Model response did not include a valid Decision line');
  }

  if (content.includes(`# Reviewer Review: ${payload.taskId}`)) {
    return content.trim();
  }

  return buildReviewDocument({
    taskId: payload.taskId,
    taskNum: payload.taskNum,
    reviewerName: payload.reviewer?.name || 'Grok Build',
    decision,
    summary: 'Automated review completed via xAI engine. See model output sections below.',
    findings: {
      nonBlocking: ['Full model output was normalized into the standard review template.']
    },
    tradeoffs: content.trim()
  });
}

async function runDeterministicReview({ payload }) {
  const taskId = payload.taskId;
  const taskNum = payload.taskNum;
  const reviewerName = payload.reviewer?.name || 'Grok Build';

  if (!payload.reviewRequest || !payload.reviewRequest.trim()) {
    return buildReviewDocument({
      taskId,
      taskNum,
      reviewerName,
      decision: 'REQUEST_CHANGES',
      summary: 'Review request content was missing from the dispatch payload.',
      findings: { blocking: ['reviewRequest field is empty — run trigger-review.js before dispatch-review.js'] }
    });
  }

  const hasDiff = Boolean(payload.diff && payload.diff.trim());
  const decision = hasDiff ? 'APPROVE' : 'REQUEST_CHANGES';

  return buildReviewDocument({
    taskId,
    taskNum,
    reviewerName,
    decision,
    summary: hasDiff
      ? `Deterministic test engine accepted ${taskId} because task, review request, and diff were present.`
      : `Deterministic test engine requested changes for ${taskId} because no diff patch was attached.`,
    findings: {
      blocking: hasDiff ? [] : ['Missing REVIEWS/review_diff_' + taskNum + '.patch in reviewer payload'],
      nonBlocking: ['Generated by REVIEWER_ENGINE=deterministic for CI and local adapter smoke tests only.']
    },
    tradeoffs: 'Deterministic engine is not a production reviewer; configure REVIEWER_ENGINE=xai with XAI_API_KEY for real Grok reviews.'
  });
}

function resolveGrokBin(env = process.env) {
  const candidates = [
    env.GROK_BIN,
    path.join(os.homedir(), '.grok', 'bin', 'grok'),
    'grok'
  ].filter(Boolean);

  for (const candidate of candidates) {
    if (candidate === 'grok' || fs.existsSync(candidate)) {
      return candidate;
    }
  }

  return 'grok';
}

function runGrokTuiCommand({ grokBin, args, cwd, env, timeoutMs }) {
  return new Promise((resolve, reject) => {
    const child = spawn(grokBin, args, {
      cwd,
      env: { ...process.env, ...env },
      stdio: ['ignore', 'pipe', 'pipe']
    });

    let stdout = '';
    let stderr = '';
    child.stdout.on('data', chunk => { stdout += chunk.toString(); });
    child.stderr.on('data', chunk => { stderr += chunk.toString(); });

    const timer = setTimeout(() => {
      child.kill('SIGTERM');
      reject(new Error(`Grok Build TUI timed out after ${timeoutMs}ms`));
    }, timeoutMs);

    child.on('error', error => {
      clearTimeout(timer);
      reject(error);
    });

    child.on('close', code => {
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(
          `Grok Build TUI exited with code ${code}: ${(stderr || stdout).trim() || 'no output'}`
        ));
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

function buildTuiReviewPrompt({ payload, rootDir }) {
  const taskId = payload.taskId;
  const taskNum = payload.taskNum;
  const reviewPath = payload.expectedReviewPath || `REVIEWS/review_${taskNum}.md`;
  const diffPath = path.join(rootDir, 'REVIEWS', `review_diff_${taskNum}.patch`);
  const hasDiff = Boolean(payload.diff && payload.diff.trim()) || fs.existsSync(diffPath);

  return [
    'You are Grok Build (Layer 2 reviewer) for the agent-cowork (pixel-agent-desk) governance workflow.',
    `Review ${taskId} and write the formal review file to ${reviewPath}.`,
    'Follow TEAM_RULES.md section 10 and REVIEWS/README.md.',
    `Use header "# Grok Build Review: ${taskId}" with "- **Reviewer**: Grok Build" and an exact decision line "- **Decision**: APPROVE" or REQUEST_CHANGES or REJECT.`,
    `Read TASKS/task_${taskNum}.md, REVIEWS/review_request_${taskNum}.md${hasDiff ? `, and REVIEWS/review_diff_${taskNum}.patch` : ''}.`,
    'Write only the review markdown file. Do not merge branches or modify implementation code outside REVIEWS/.',
    'End the file with: *Review authored by Grok Build (Layer 2).*'
  ].join(' ');
}

async function callTuiGrokReview({ payload, rootDir, env = process.env }) {
  const taskNum = payload.taskNum;
  const taskId = payload.taskId || `TASK-${taskNum}`;
  const reviewPath = path.join(rootDir, payload.expectedReviewPath || `REVIEWS/review_${taskNum}.md`);
  const grokBin = resolveGrokBin(env);
  const timeoutMs = Number(env.REVIEWER_TUI_TIMEOUT_MS || 600000);
  const prompt = buildTuiReviewPrompt({ payload, rootDir });

  await runGrokTuiCommand({
    grokBin,
    args: [
      '-p', prompt,
      '--cwd', rootDir,
      '--always-approve',
      '--disallowed-tools', 'web_search,web_fetch'
    ],
    cwd: rootDir,
    env,
    timeoutMs
  });

  if (!fs.existsSync(reviewPath)) {
    throw new Error(`Grok Build TUI did not write ${reviewPath}`);
  }

  const markdown = fs.readFileSync(reviewPath, 'utf8');
  const decision = extractDecisionFromModelText(markdown);
  if (!decision) {
    throw new Error(`Grok Build TUI wrote ${reviewPath} but it is missing a valid Decision line`);
  }

  return markdown.trim();
}

async function runReviewEngine({ payload, rootDir, env = process.env }) {
  const engine = (env.REVIEWER_ENGINE || 'tui').toLowerCase();

  if (engine === 'deterministic') {
    return runDeterministicReview({ payload });
  }

  if (engine === 'tui' || engine === 'grok-build' || engine === 'grok_tui') {
    return callTuiGrokReview({ payload, rootDir, env });
  }

  if (engine === 'xai' || engine === 'grok') {
    return callXaiReview({ payload, env });
  }

  throw new Error(`Unsupported REVIEWER_ENGINE="${engine}". Use deterministic, tui, or xai.`);
}

function writeReviewJobStatus({ rootDir, taskNum, status, details = {} }) {
  const jobPath = path.join(rootDir, 'REVIEWS', `review_job_${taskNum}.json`);
  fs.mkdirSync(path.dirname(jobPath), { recursive: true });
  fs.writeFileSync(
    jobPath,
    `${JSON.stringify({
      taskNum,
      status,
      updatedAt: new Date().toISOString(),
      ...details
    }, null, 2)}\n`,
    'utf8'
  );
  return jobPath;
}

async function executeLocalReview({ rootDir, payload, env = process.env }) {
  const taskNum = payload.taskNum;
  const taskId = payload.taskId || `TASK-${taskNum}`;
  const reviewerName = payload.reviewer?.name || 'Grok Build';
  const reviewPath = path.join(rootDir, payload.expectedReviewPath || `REVIEWS/review_${taskNum}.md`);

  writeReviewJobStatus({ rootDir, taskNum, status: 'running', details: { reviewPath } });

  try {
    const markdown = await runReviewEngine({ payload, rootDir, env });
    const decision = extractDecisionFromModelText(markdown) || normalizeDecision(
      markdown.match(/-\s*\*\*Decision\*\*:\s*(APPROVE|REQUEST_CHANGES|REJECT)/i)?.[1]
    );

    if (!decision) {
      throw new Error('Generated review is missing a valid Decision line');
    }

    fs.mkdirSync(path.dirname(reviewPath), { recursive: true });
    fs.writeFileSync(reviewPath, `${markdown.trim()}\n`, 'utf8');

    writeReviewJobStatus({
      rootDir,
      taskNum,
      status: 'completed',
      details: { reviewPath, decision }
    });

    return { reviewPath, decision };
  } catch (error) {
    const failureReview = buildEngineFailureReview({
      taskId,
      taskNum,
      reviewerName,
      errorMessage: error.message
    });

    fs.mkdirSync(path.dirname(reviewPath), { recursive: true });
    fs.writeFileSync(reviewPath, `${failureReview.trim()}\n`, 'utf8');

    writeReviewJobStatus({
      rootDir,
      taskNum,
      status: 'failed',
      details: { reviewPath, error: error.message }
    });

    return { reviewPath, decision: 'REQUEST_CHANGES', error: error.message };
  }
}

module.exports = {
  buildReviewPrompt,
  buildTuiReviewPrompt,
  callTuiGrokReview,
  executeLocalReview,
  runDeterministicReview,
  runReviewEngine,
  writeReviewJobStatus
};